# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-21 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='名称')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '地市',
                'verbose_name_plural': '地市',
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theclass', models.CharField(choices=[('晨曦', '晨曦'), ('晨光', '晨光'), ('曙光', '曙光'), ('朝阳', '朝阳'), ('旭日', '旭日')], default='晨曦', max_length=50, verbose_name='班级')),
                ('master', models.CharField(max_length=50, verbose_name='班主任')),
            ],
            options={
                'verbose_name': '分班',
                'verbose_name_plural': '分班',
            },
        ),
        migrations.CreateModel(
            name='Import_Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_count', models.IntegerField(default=0, verbose_name='条数')),
                ('remarks', models.CharField(max_length=255, verbose_name='备注')),
                ('is_saved', models.BooleanField(default=False, verbose_name='保存')),
                ('search_date', models.DateField(auto_now_add=True, verbose_name='添加日期')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='名称')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_of_city', to='edu.City', verbose_name='所属地市')),
            ],
            options={
                'verbose_name': '法人',
                'verbose_name_plural': '法人',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='名称')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('begin_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '期次',
                'verbose_name_plural': '期次',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=50, verbose_name='性别')),
                ('company', models.CharField(max_length=50, verbose_name='单位')),
                ('nation', models.CharField(max_length=50, verbose_name='民族')),
                ('birth', models.CharField(max_length=50, verbose_name='生日')),
                ('party', models.CharField(max_length=50, verbose_name='组织关系')),
                ('job', models.CharField(max_length=50, verbose_name='职务')),
                ('phone', models.CharField(max_length=50, verbose_name='电话')),
                ('remarks', models.CharField(max_length=50, verbose_name='备注')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('inport_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_import', to='edu.Import_Summary', verbose_name='导入')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_of_org', to='edu.Org', verbose_name='法人')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_of_school', to='edu.School', verbose_name='期次')),
            ],
            options={
                'verbose_name': '学员',
                'verbose_name_plural': '学员',
            },
        ),
        migrations.AddField(
            model_name='import_summary',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu_of_import', to='edu.School', verbose_name='期次'),
        ),
        migrations.AddField(
            model_name='classes',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu_of_class', to='edu.School', verbose_name='期次'),
        ),
        migrations.AddField(
            model_name='classes',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_of_class', to='edu.Student', verbose_name='学员'),
        ),
    ]
