# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-20 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='名称')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '地市',
                'verbose_name_plural': '地市',
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theclass', models.IntegerField(choices=[(1, '晨曦'), (2, '晨光'), (3, '曙光'), (4, '朝阳'), (5, '旭日')], default=1, verbose_name='班级')),
                ('master', models.CharField(max_length=50, verbose_name='班主任')),
            ],
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='名称')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_of_city', to='edu.City', verbose_name='所属地市')),
            ],
            options={
                'verbose_name': '法人',
                'verbose_name_plural': '法人',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='名称')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '期次',
                'verbose_name_plural': '期次',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('nation', models.CharField(max_length=50, verbose_name='民族')),
                ('birth', models.CharField(max_length=50, verbose_name='生日')),
                ('party', models.CharField(max_length=50, verbose_name='组织关系')),
                ('job', models.CharField(max_length=50, verbose_name='职务')),
                ('phone', models.CharField(max_length=50, verbose_name='电话')),
                ('remarks', models.CharField(max_length=50, verbose_name='备注')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_of_org', to='edu.Org', verbose_name='法人')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.School'),
        ),
        migrations.AddField(
            model_name='classes',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Student'),
        ),
    ]
