# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-20 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name': '分班', 'verbose_name_plural': '分班'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学员', 'verbose_name_plural': '学员'},
        ),
        migrations.AlterField(
            model_name='classes',
            name='theclass',
            field=models.CharField(choices=[('晨曦', '晨曦'), ('晨光', '晨光'), ('曙光', '曙光'), ('朝阳', '朝阳'), ('旭日', '旭日')], default='晨曦', max_length=50, verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=50, verbose_name='性别'),
        ),
    ]
