# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-20 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_auto_20190620_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='begin_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='开始日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='结束日期'),
            preserve_default=False,
        ),
    ]
